
include: package:lints/recommended.yaml


analyzer:
  errors:
    prefer_relative_imports: error
    unused_element: ignore
    unused_catch_clause: ignore
    unused_import: ignore
    unnecessary_import: ignore
    dead_null_aware_expression: ignore
  exclude:
    - extension/**
    - .clone-june-flutter/**

linter:
  rules:
    prefer_relative_imports: true
    avoid_print: false
    prefer_const_constructors_in_immutables: false
    avoid_relative_lib_imports: false
    constant_identifier_names: false
    file_names: false
    prefer_function_declarations_over_variables: false
    prefer_const_constructors: false # 나중에 릴리즈 할때 이 옵션 해제해서 한번에 처리
    prefer_const_literals_to_create_immutables: false # 나중에 릴리즈 할때 이 옵션 해제해서 한번에 처리
    sized_box_for_whitespace: false
    #    unnecessary_import: false
    non_constant_identifier_names: false
    library_private_types_in_public_api: false
    no_leading_underscores_for_local_identifiers: false
    unused_element: false