name: juneflutter_cli
description: A command-line for JuneFlutter.
version: 0.0.4
repository: https://github.com/melodysdreamj/juneflutter_cli

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  juneflutter: juneflutter_cli
