name: juneflow_cli
description: A command-line for JuneFlow.
version: 0.8.1
repository: https://github.com/melodysdreamj/juneflow_cli

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  june: juneflow_cli
